apiVersion: v1  
kind: Service  
metadata:   
  name: couchbase-Worker-service  
  labels:   
    app: couchbase-Worker-service  
spec:   
  ports:  
    - port: 8091  
  selector:   
    app: couchbase-worker-pod  
  type: LoadBalancer
